name: MainTest

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify a version"
        required: false
      ref:
        description: "Branch, tag or hash (default: main)"
        required: false
        default: "main"
      type:
        description: "Select the deployment environment"
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{ inputs.ref }}

      - name: Restore dependencies
        run: dotnet restore UnitTest/UnitTest.csproj

      - name: Run Deployment Script
        run: |
          if "%GITHUB_ENV_TYPE%" == "staging" (
            dotnet run --project PerformanceTest/PerformanceTest.csproj --configuration Release /p:TestType=RedBlackTree
          ) else if "%GITHUB_ENV_TYPE%" == "production" (
            echo 你好，世界
          ) else (
            echo Invalid environment selected!
            exit 1
          )
        shell: cmd
        env:
          GITHUB_ENV_TYPE: ${{ inputs.type }}