name: enter_label

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify a version"
        required: false
      ref:
        description: "Branch, tag or hash (default: develop)"
        required: false
        default: "develop"
      type:
        description: "Select the deployment environment"
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-test:
    runs-on: myrunner1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{ inputs.ref }}

      - name: Run Deployment Script
        run: |
          if "%{{ github.event.inputs.type }}" == "staging" (
            call Do-Confuser_Setup_Staging.bat staging
          ) else if "%{{ github.event.inputs.type }}" == "production" (
            call Do-Confuser_Setup_Production.bat
          ) else (
            echo Invalid environment selected!
            exit 1
          )
        shell: cmd